# Generated by Django 3.2 on 2021-05-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_roll', models.IntegerField()),
                ('Stu_name', models.CharField(max_length=20)),
                ('Stu_dept', models.CharField(max_length=15)),
                ('Stu_group', models.CharField(max_length=1)),
            ],
        ),
    ]
