# Generated by Django 3.2 on 2021-05-17 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attnd', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Stu_name',
            new_name='stu_name',
        ),
    ]
