# Generated by Django 3.2 on 2021-05-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attnd', '0002_rename_stu_name_student_stu_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stu_name',
            new_name='Stu_name',
        ),
    ]
