# Generated by Django 3.2 on 2021-05-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attnd', '0004_studentattendence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendence',
            name='student_present',
            field=models.CharField(choices=[('present', 'p'), ('absent', 'a')], max_length=20),
        ),
    ]
