# Generated by Django 3.2 on 2021-05-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attnd', '0005_alter_studentattendence_student_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendence',
            name='student_present',
            field=models.CharField(choices=[('present', 'P'), ('absent', 'A')], max_length=20),
        ),
    ]
