# Generated by Django 3.2 on 2021-05-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attnd', '0006_alter_studentattendence_student_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendence',
            name='attendance_date',
            field=models.DateField(auto_now=True),
        ),
    ]
