# Generated by Django 3.2 on 2021-05-19 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attnd', '0009_auto_20210519_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentattendence',
            old_name='Student_dept',
            new_name='student_dept',
        ),
        migrations.RenameField(
            model_name='studentattendence',
            old_name='Student_group',
            new_name='student_group',
        ),
    ]
