# Generated by Django 3.2 on 2021-06-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attnd', '0011_rename_student_dept_studentattendence_student_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendence',
            name='student_department',
            field=models.CharField(choices=[('Bca', 'Bca'), ('Computer Science', 'Computer Science')], default='', max_length=55),
        ),
    ]
